services:
  garage:
    image: dxflrs/garage:v2.1.0
    container_name: gentle-space-garage
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./docker/garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

volumes:
  garage_meta:
  garage_data:
